---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
   - destroy
   - create
   - converge
   - destroy
