---
dependency:
  name: galaxy
driver:
  name: docker
  # options:
  #   D: true
  #   vv: true
platforms:
  - name: centos7
    image: quay.io/centos/centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
   - destroy
   - create
   - converge
   - destroy
