---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true
platforms:
  - name: centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true   

  # - name: ubuntu
  #   image: geerlingguy/docker-ubuntu2004-ansible:latest
  #   command: /sbin/init
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   pre_build_image: true 
    
# lint: | 
#   set -e
#   yamllint .
#   ansible-lint .

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
   - create
   - converge
   - lint
   - idempotence
   - verify
   - destroy
   - cleanup
   - destroy
  
